### ISSUE TITLE
Splits occur when they shouldn't...

### ISSUE THREAD

**Issue by ralfbergs** [ddennedy/dvgrab#3]
Hi,

I'm using dvgrab 3.5 from Ubuntu 16.10 to grab video footage from a MiniDV camcorder.

Ideally dvgrab would only auto-split files where there is actually a discontinuation in timecode or the "new recording" flag set -- but for some reason this doesn't work in a reliable way, dvgrab splits files where it shouldn't, because it's a contiguous recording.

So I tried using `--autosplit=5` to make it create separate files only if there is at least a gap of 5 secs. But not even this works properly, too many splits again.

Any clue what's going on? Can I somehow help debugging this? Would be really great if this could be fixed, as with iMovie under macOS or Movie Maker under Windoze I can't capture some of my tapes at all (strangely enough, also too many splits occur, or there is an error message "no data from device.")

Thanks!

**Comment by ddennedy** [comment]
Shouldn't or not as you want/expected? There are a number of factors to determine splitting, and you have to figure out the options to get the results you want if you do not like them. dvgrab is an old program that has had its logic refined and tested over time. Not saying there aren't any remaining bugs, but you will likely have to debug it because I do not use or maintain it much anymore. In fact, I am quite hesitant to change it at this point for fear of breaking it due to lack of activity and a full regression test plan. Here is where the bulk of splitting logic occurs:
https://github.com/ddennedy/dvgrab/blob/master/filehandler.cc#L323

As you can see there are factors such as file size, frame count, scene change flag, and timecode discontinuity. The latter two comes from data in the DV stream, which is a digital data transfer from the device over firewire (as opposed to data synthesized in a driver, library, or the app). I think the only option default you might need to override is -size, which defaults to 1024 MiB.

In order to claim that autosplit is not working, you need to provide some evidence other than claiming "splits files where it shouldn't". Did you analyze the DV data? Show the numbers and verify that file size was not a factor.

**Comment by ralfbergs** [comment]
My approach was to use the following command-line:
`dvgrab --autosplit --timestamp --size 0 --rewind Florida-`
Should this not always result in the same split? How come that if I repeat this, I get completely differently-sized files, and a different number? Sometimes one recording is split into many, many files (like 10 or 20), while sometimes it will result in a single file only or maybe two?

As I wrote in issue #5 I can't tell where the root cause may be, due to lack of experience and knowledge with this technology...

Can you please guide me what kind of information I have to provide so that you could check stuff for me?

Thanks a lot for your support.

**Comment by ralfbergs** [comment]
It turned out that this was an issue the cam is responsible for. See #5 for details.

**Comment by EpicLPer** [comment]
I don't really want to bring up a dead issue again but I also don't want to create a new one before discussing it here.
I have quite the opposite issue, for me dvgrab sometimes doesn't autosplit where it should even when there are huge gaps of 2 or 3 seconds with no datastream. And sometimes I do have the same behavior as described here that it would sometimes think that it's time to do a split now despite it still being the same scene, timecode, etc.

**Comment by greatestradioshow** [comment]
Hello,
I know this is an ancient thread, but still I came across this issue with my tapes.
While WinDV and ScenalyzerLive recognize the different segments/scenes on my tape correctly, dvgrab doesn't.
It looks like that the timestamp is not considered correctly. 

I guess beside using "--autosplit --timestamp" there is nothing I can set, or?

**Comment by greatestradioshow** [comment]
Hello,
I know this is an ancient thread, but still I came across this issue with my tapes.
While WinDV and ScenalyzerLive recognize the different segments/scenes on my tape correctly, dvgrab doesn't.
It looks like that the timestamp is not considered correctly but in my case two segments were saved as one.

I guess beside using "--autosplit --timestamp" there is nothing I can set, or?
